//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34014
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SerienbriefMailer.Lang {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class de_DE {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal de_DE() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SerienbriefMailer.Lang.de-DE", typeof(de_DE).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PDF-Serienbrief-Mailer ähnelt.
        /// </summary>
        internal static string applicationName {
            get {
                return ResourceManager.GetString("applicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anhang ähnelt.
        /// </summary>
        internal static string attachment {
            get {
                return ResourceManager.GetString("attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anhänge ähnelt.
        /// </summary>
        internal static string attachments {
            get {
                return ResourceManager.GetString("attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wählen Sie eine CSV-Datei. ähnelt.
        /// </summary>
        internal static string btnCSV_SelectFile {
            get {
                return ResourceManager.GetString("btnCSV_SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CSV-Datei erfolgreich eingelesen. ähnelt.
        /// </summary>
        internal static string btnCsvSuccess {
            get {
                return ResourceManager.GetString("btnCsvSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Laden Sie eine CSV-Datei hoch. ähnelt.
        /// </summary>
        internal static string btnCsvUlpodFile {
            get {
                return ResourceManager.GetString("btnCsvUlpodFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wählen Sie eine PDF-Datei aus. ähnelt.
        /// </summary>
        internal static string btnPdfChooseFile {
            get {
                return ResourceManager.GetString("btnPdfChooseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Noch keine PDF-Datei ausgewählt. ähnelt.
        /// </summary>
        internal static string btnPdfFileSelect {
            get {
                return ResourceManager.GetString("btnPdfFileSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sie haben nichts gewählt. ähnelt.
        /// </summary>
        internal static string btnPdfFileSelected_EmptySelection {
            get {
                return ResourceManager.GetString("btnPdfFileSelected_EmptySelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sie haben keine PDF-Datei gewählt. ähnelt.
        /// </summary>
        internal static string btnPdfFileSelected_InappropriateSuffix {
            get {
                return ResourceManager.GetString("btnPdfFileSelected_InappropriateSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler: Die gewählte Datei ist keine PDF-Datei. Die Dateiendung muss lauten: *.pdf oder *.PDF&quot;) ähnelt.
        /// </summary>
        internal static string btnPdfFileSelected_InappropriateSuffixLog {
            get {
                return ResourceManager.GetString("btnPdfFileSelected_InappropriateSuffixLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keine Datei gewählt oder nicht lesbar. Geschützte Datei? ähnelt.
        /// </summary>
        internal static string btnPdfFileSelected_NotReadable {
            get {
                return ResourceManager.GetString("btnPdfFileSelected_NotReadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler: Ist sie geschützt? Lässt sich die Datei überhaupt an einen Drucker senden? Stichwort: DRM. Ein möglicher Grund kann sein, dass die Datei in irgendeiner Form geschützt ist. Das gilt beispielsweise oft für eBooks. Denkbar ist weiterhin, dass zwar die Dateiendung eine PDF-Datei behauptet, der tatsächliche Typ aber abweicht.In jedem Fall kann diese Datei nicht verarbeitet werden.Lässt sich die Datei mit einem PDF-drucken? Wenn ja, dann kehren Sie mit dem PDF-Druck hierher zurück. ähnelt.
        /// </summary>
        internal static string btnPdfFileSelected_NotReadableLog {
            get {
                return ResourceManager.GetString("btnPdfFileSelected_NotReadableLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  E-Mail-Adresse(n). Siehe Protokoll. ähnelt.
        /// </summary>
        internal static string btnPdfFileSelected_Ok {
            get {
                return ResourceManager.GetString("btnPdfFileSelected_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erfolg: Es wurde eine PDF-Datei erfolgreich eingelesen. ähnelt.
        /// </summary>
        internal static string btnPdfFileSelected_OkLog {
            get {
                return ResourceManager.GetString("btnPdfFileSelected_OkLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abbrechen ähnelt.
        /// </summary>
        internal static string btnSendMails_Cancel {
            get {
                return ResourceManager.GetString("btnSendMails_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die E-Mails senden! ähnelt.
        /// </summary>
        internal static string btnSendMails_Send {
            get {
                return ResourceManager.GetString("btnSendMails_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erneut senden! ähnelt.
        /// </summary>
        internal static string btnSendMails_SendAgain {
            get {
                return ResourceManager.GetString("btnSendMails_SendAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pause ähnelt.
        /// </summary>
        internal static string btnSendMailsPause {
            get {
                return ResourceManager.GetString("btnSendMailsPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Senden! ähnelt.
        /// </summary>
        internal static string btnSendMailsSend {
            get {
                return ResourceManager.GetString("btnSendMailsSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Protokoll anzeigen. ähnelt.
        /// </summary>
        internal static string btnShowLog {
            get {
                return ResourceManager.GetString("btnShowLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CSV-Dateien ähnelt.
        /// </summary>
        internal static string csvFiles {
            get {
                return ResourceManager.GetString("csvFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es fehlt eine Kopfzeile in der CSV-Datei... ähnelt.
        /// </summary>
        internal static string CsvHeadlineMissing {
            get {
                return ResourceManager.GetString("CsvHeadlineMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datei(en) ähnelt.
        /// </summary>
        internal static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PDF-Serienbrief-Mailer ähnelt.
        /// </summary>
        internal static string formTitle {
            get {
                return ResourceManager.GetString("formTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wählen Sie eine CSV-Datei (optional). ähnelt.
        /// </summary>
        internal static string groupBox4ChooseCsvFile {
            get {
                return ResourceManager.GetString("groupBox4ChooseCsvFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anschreiben ähnelt.
        /// </summary>
        internal static string groupBoxMail {
            get {
                return ResourceManager.GetString("groupBoxMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PDF-Datei für Serienbriefversand. ähnelt.
        /// </summary>
        internal static string groupBoxPdf {
            get {
                return ResourceManager.GetString("groupBoxPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abbruch in Zeile ähnelt.
        /// </summary>
        internal static string InterruptCsvReading {
            get {
                return ResourceManager.GetString("InterruptCsvReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Letzte Nachricht erreicht. Blättern Sie zurück. ähnelt.
        /// </summary>
        internal static string LastMessageInOutboxReechedGoBack {
            get {
                return ResourceManager.GetString("LastMessageInOutboxReechedGoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nachricht ähnelt.
        /// </summary>
        internal static string lblBody {
            get {
                return ResourceManager.GetString("lblBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Jetzt müssen Sie noch eine PDF-Datei wählen ... ähnelt.
        /// </summary>
        internal static string lblEmailSuccessNext {
            get {
                return ResourceManager.GetString("lblEmailSuccessNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Test-E-Mail an Sie selbst erfolgreich. ähnelt.
        /// </summary>
        internal static string lblEmailTestmailSuccess {
            get {
                return ResourceManager.GetString("lblEmailTestmailSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Testmail erfolgreich gesendet. ähnelt.
        /// </summary>
        internal static string lblEmailTestmailSuccessLog {
            get {
                return ResourceManager.GetString("lblEmailTestmailSuccessLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Nachricht darf nicht leer sein. ähnelt.
        /// </summary>
        internal static string lblMailBodyEmpty {
            get {
                return ResourceManager.GetString("lblMailBodyEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Formulieren Sie ein Anschreiben. (Optional mit Platzhaltern) ähnelt.
        /// </summary>
        internal static string lblMailComposeMail {
            get {
                return ResourceManager.GetString("lblMailComposeMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Geben Sie einen Betreff ein. ähnelt.
        /// </summary>
        internal static string lblMailSubjectEmpty {
            get {
                return ResourceManager.GetString("lblMailSubjectEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SMTP-Server konfigurieren. ähnelt.
        /// </summary>
        internal static string lblSmptConfigureSmtp {
            get {
                return ResourceManager.GetString("lblSmptConfigureSmtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Betreff ähnelt.
        /// </summary>
        internal static string lblSubject {
            get {
                return ResourceManager.GetString("lblSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hallo [[Alias1]] [[Alias2]],\n... ähnelt.
        /// </summary>
        internal static string MailDefaultBody {
            get {
                return ResourceManager.GetString("MailDefaultBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nachricht für [[Alias1]] ähnelt.
        /// </summary>
        internal static string MailDefaultSubject {
            get {
                return ResourceManager.GetString("MailDefaultSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mehrfachauswahl ähnelt.
        /// </summary>
        internal static string multiplePdfFilesSelected {
            get {
                return ResourceManager.GetString("multiplePdfFilesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keine Adresse gefunden. Evtl. ist die Datei nicht lesbar. ähnelt.
        /// </summary>
        internal static string NoMailAddress {
            get {
                return ResourceManager.GetString("NoMailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nr. ähnelt.
        /// </summary>
        internal static string number {
            get {
                return ResourceManager.GetString("number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Seite(n) ähnelt.
        /// </summary>
        internal static string Pages {
            get {
                return ResourceManager.GetString("Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Blättern Sie durch den Postausgang. ähnelt.
        /// </summary>
        internal static string pdfFileBrowseInstruction {
            get {
                return ResourceManager.GetString("pdfFileBrowseInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PDF-Dateien ähnelt.
        /// </summary>
        internal static string pdfFiles {
            get {
                return ResourceManager.GetString("pdfFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zeile ähnelt.
        /// </summary>
        internal static string row {
            get {
                return ResourceManager.GetString("row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die muss mit einer E-Mail beginnen. ähnelt.
        /// </summary>
        internal static string rowErrorMissingEmail {
            get {
                return ResourceManager.GetString("rowErrorMissingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mailserverkonfiguration noch nicht ok. ähnelt.
        /// </summary>
        internal static string smtpConfigurationNotOk {
            get {
                return ResourceManager.GetString("smtpConfigurationNotOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SMTP-Server Einstellungen unvollständig. ähnelt.
        /// </summary>
        internal static string smtpIncomplete {
            get {
                return ResourceManager.GetString("smtpIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte nur (maximal fünf) Ziffern eingeben. ähnelt.
        /// </summary>
        internal static string SmtpPortNotOk {
            get {
                return ResourceManager.GetString("SmtpPortNotOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Falsche Portnummer eingegeben. Die Portnummer darf nur aus Ziffern bestehen. Typische Werte sind 25, 465, ... ähnelt.
        /// </summary>
        internal static string SmtpPortNotOkLog {
            get {
                return ResourceManager.GetString("SmtpPortNotOkLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Geben Sie eine vollständige E-Mail ein. ähnelt.
        /// </summary>
        internal static string SmtpUserMailNotOk {
            get {
                return ResourceManager.GetString("SmtpUserMailNotOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wenn Sie diese E-Mail sehen, haben Sie den SMTP-Server erfolgreich konfiguriert.. ähnelt.
        /// </summary>
        internal static string testmailBody {
            get {
                return ResourceManager.GetString("testmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Testmail konnte nicht gesendet werden:  ähnelt.
        /// </summary>
        internal static string testmailError {
            get {
                return ResourceManager.GetString("testmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ist der Firewallport geöffnet? ähnelt.
        /// </summary>
        internal static string testmailFirewallClosed {
            get {
                return ResourceManager.GetString("testmailFirewallClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passworteingabe unvollständig? Tippfehler? ähnelt.
        /// </summary>
        internal static string testmailPasswordWrong {
            get {
                return ResourceManager.GetString("testmailPasswordWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Test-E-Mail des Serienbrief-Senders ähnelt.
        /// </summary>
        internal static string testmailSubject {
            get {
                return ResourceManager.GetString("testmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Platzhalter gefunden. Laden Sie eine passende CSV-Datei. ähnelt.
        /// </summary>
        internal static string UploadCsv {
            get {
                return ResourceManager.GetString("UploadCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Willkommen zum PDF-Serienbrief-Mailer ähnelt.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
